### ISSUE TITLE
Contract Addresses

### ISSUE THREAD

**Issue by Neros0** [AeroDump/contracts#10]
AeroDumpAttestations: 0xe734076F9B3C4Af1920e92B218B4C3691a1b02d7
https://base-sepolia.blockscout.com/address/0xe734076F9B3C4Af1920e92B218B4C3691a1b02d7?tab=contract

AerodumpOFTAdapter: 0x0b7C1E3eF86adf0b33b0d542271FdDe8369699Dc
https://base-sepolia.blockscout.com/address/0x0b7C1E3eF86adf0b33b0d542271FdDe8369699Dc?tab=contract_code

USDC Base Sepolia Contract: 0x036CbD53842c5426634e7929541eC2318f3dCF7e
https://sepolia.basescan.org/address/0x036cbd53842c5426634e7929541ec2318f3dcf7e#writeProxyContract

**Comment by jaskara-n** [comment]
https://automation.chain.link/base-sepolia/14286114049007338048253199516440140948950457893035655921580036376591810014964
chainlink automation registration

**Comment by Neros0** [comment]
Redployed New contracts for Demo, This is done.
