### ISSUE TITLE
Changes for rizo to be done on my branch

### ISSUE THREAD

**Issue by jaskara-n** [AeroDump/contracts#13]
1. Edit the attestations contract to send over the verified user address to a "route" contract after user calls verifyProject (_lzsend).
2. Build a route contract that handles receiving of the sent data from attestations to the route.
3. Inside the route contract send over the same user address to all the adapters deployed for various currencies.
4. Make the current OFTAdapter.sol compose receiver contract for usdc and maybe add another currency support too to test it all out.

**Comment by jaskara-n** [comment]
5. Try deploying the adapters on hedera  that will receive the composed message
6. Attestations and Routes can be on home network ie base Sepolia and all the adapters for various currencies can be on header
7. Checkout the current scripts to see the flow, here is the link that will help you deploy and send omnichain messages, all this is done in the scripts but just for reference
https://docs.layerzero.network/v2/developers/evm/oapp/overview

**Comment by Neros0** [comment]
Done
