### ISSUE TITLE
#2 Changes for Rizo to be done on my branch

### ISSUE THREAD

**Issue by jaskara-n** [AeroDump/contracts#15]
1. If u want check by sending plan string from attestation using function send() and decoding and saving it in composer.
2. First see if you really get the address on both composer(automatically received) and adapter(using directly calling adapter contract function), then proceed in making functions n all.
3. Send msg.sender in verifyProject() to composer.
4. decode the address in composer inside _lzreceive and either directly call all the adapters inside _lzreceive to send the address from composer to adapter using a function on adapter called maybe updateVerifiedUsers (because both contracts live on same chain.
5. All setPeers and setSchemas, setEid are already out of the box in my scripts, you just need to hardcode the contract addresses and run the script on the correct network (use your logic or see the comment on top of each script, network is mentioned)
6. TEST EVERYTHING OUT ONCHAIN, ALL SCRIPTS ARE PROVIDED.
7. you will need to update the script : console, because currently it show the global var data, received in the destination contract(composer) , basically currently when lzreceive is provoked it updates a global var only nothing else it does.

**Comment by Neros0** [comment]
Done
